# Generated by Django 5.2.7 on 2025-12-13 19:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0002_alter_asset_description_alter_asset_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asset',
            name='price',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='stock',
        ),
        migrations.AddField(
            model_name='asset',
            name='asset_tag',
            field=models.CharField(default='TEMP-ASSET', max_length=100, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='asset',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='asset',
            name='category',
            field=models.CharField(default='TEMP-ASSET', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='asset',
            name='location',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='asset',
            name='purchase_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='serial',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='asset',
            name='status',
            field=models.CharField(choices=[('ready', 'Ready'), ('deployed', 'Deployed'), ('repair', 'Repair')], default='ready', max_length=20),
        ),
        migrations.AlterField(
            model_name='asset',
            name='description',
            field=models.TextField(blank=True, default='TEMP-ASSET'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='asset',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='assets/'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
