# Generated by Django 5.2.9 on 2025-12-21 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0004_accessory_component_consumable_license_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='license',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
