# Generated by Django 5.2.9 on 2025-12-21 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0005_asset_is_deleted_license_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='license',
            name='licensed_to_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='license',
            name='licensed_to_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
