# Generated by Django 5.2.9 on 2025-12-21 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0006_license_licensed_to_email_license_licensed_to_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='status',
            field=models.CharField(choices=[('ready', 'Ready'), ('deployed', 'Deployed'), ('archived', 'Archived')], default='ready', max_length=20),
        ),
    ]
