# Generated by Django 5.2.9 on 2025-12-21 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0007_alter_asset_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='accessory',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
