# Generated by Django 5.2.9 on 2025-12-21 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0008_accessory_is_deleted'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='consumable',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='consumable',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
