# Generated by Django 5.2.9 on 2025-12-21 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0009_alter_consumable_options_consumable_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='consumable',
            name='item_no',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='consumable',
            name='min_quantity',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='consumable',
            name='model_no',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='consumable',
            name='order_number',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='consumable',
            name='purchase_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='consumable',
            name='unit_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
