# Generated by Django 5.2.9 on 2025-12-21 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0010_consumable_item_no_consumable_min_quantity_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='component',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='component',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='component',
            name='min_quantity',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='component',
            name='model_no',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='component',
            name='order_number',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='component',
            name='purchase_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='component',
            name='serial',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='component',
            name='unit_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
