# Generated by Django 5.2.9 on 2025-12-21 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0011_alter_component_options_component_is_deleted_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accessory',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='accessory',
            name='min_quantity',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='accessory',
            name='model_no',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
