# Generated by Django 5.2.9 on 2025-12-21 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0012_alter_accessory_options_accessory_min_quantity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='accessory',
            name='device_image',
            field=models.ImageField(blank=True, null=True, upload_to='accessories/'),
        ),
    ]
